<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class IpConditionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = Carbon::now();

        DB::table('ip_condition')->insert([
            // category: 1-Fresh Fruit, 2-Product, 3-Fresh Vegetables, 4-Planting Material, 5-Planting Media, 6-Others,7-Woods Product,8-Fertilizer,9-Animal Feed
            [
                'category' => 1,
                'item_name' => 'CORN',
                'addional_condition' => '<pre>7) The issuance of Phytosanitary Certificate (PC) should be based on the Malaysian Permit Import (IP)  reference number :(IPXXXXX).
8) Subject to quarantine inspection upon arrival in Kota Kinabalu.</pre>',
                'quantity_limit' => null,
                'date_limit' => null,
                'country' => json_encode(['SMY', 'CN', 'IN', 'PK']),
                'usage' => json_encode(['Fresh Produce', 'For Animal Consumption']),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category' => 1,
                'item_name' => 'DURIAN',
                'addional_condition' => '<pre>7) The issuance of Phytosanitary Certificate (PC) should be based on the Malaysian Permit Import (IP)  reference number :(IPXXXXX).
8) Subject to quarantine inspection upon arrival in Kota Kinabalu.</pre>',
                'quantity_limit' => null,
                'date_limit' => null,
                'country' => json_encode(['SWK', 'SMY']),
                'usage' => json_encode(['Fresh Produce']),
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'category' => 4,
                'item_name' => 'POKOK DURIAN',
                'addional_condition' => '<pre>"7) The issuance of Phytosanitary Certificate (PC) should be based on the Malaysian Permit Import (IP) reference number : (IPXXXX/2025). 
8) Additional Declaration: 
1. All the plants are to be cleansed of any soil.
2. The plants must be healthy and taken from an accredited farm by planting material verification scheme Department of Agriculture (DOA) of the exporting country.
3. All plants are to be dipped in 0.2% Malathion 80 E.C. + 0.4% Thiram + 0.3% Nemacur for 5 minutes (or any suitable insecticide, fungicide and Nematicide) prior to shipment.
4. Subject to quarantine inspection upon arrival in Kota Kinabalu."
</pre>',
                'quantity_limit' => null,
                'date_limit' => null,
                'country' => json_encode(['SNP']),
                'usage' => json_encode(['Planting Material']),
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'category' => 1,
                'item_name' => 'AVOCADO',
                'addional_condition' => '',
                'quantity_limit' => null,
                'date_limit' => null,
                'country' => json_encode(['AU', 'KE', 'MX', 'NZ', 'KR', 'SWK', 'ES', 'TR', 'US', 'SMY']),
                'usage' => json_encode(['Planting Material']),
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'category' => 1,
                'item_name' => 'BANANA',
                'addional_condition' => '',
                'quantity_limit' => null,
                'date_limit' => null,
                'country' => json_encode(['SWK', 'SMY']),
                'usage' => json_encode(['Planting Material']),
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'category' => 1,
                'item_name' => 'CITRUS (LEMON, ORANGE, MANDARIN, LIMES, POMELO, GRAPEFRUITS, TANGERINE)',
                'addional_condition' => '',
                'quantity_limit' => null,
                'date_limit' => null,
                'country' => json_encode(['AU', 'CN', 'EG', 'ZA', 'TH', 'US', 'SMY']),
                'usage' => json_encode(['Planting Material']),
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'category' => 1,
                'item_name' => 'CORN/MAIZE (WHOLE FRUIT)',
                'addional_condition' => '',
                'quantity_limit' => null,
                'date_limit' => null,
                'country' => json_encode(['AR', 'CN', 'IN', 'PK', 'SMY']),
                'usage' => json_encode(['Planting Material']),
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'category' => 1,
                'item_name' => 'DATES',
                'addional_condition' => '',
                'quantity_limit' => null,
                'date_limit' => null,
                'country' => json_encode(['EG', 'IN', 'ZA', 'SMY']),
                'usage' => json_encode(['Planting Material']),
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'category' => 1,
                'item_name' => 'LONGAN',
                'addional_condition' => '',
                'quantity_limit' => null,
                'date_limit' => null,
                'country' => json_encode(['TH', 'VN', 'SMY']),
                'usage' => json_encode(['Planting Material']),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category' => 1,
                'item_name' => 'LYCHEE',
                'addional_condition' => '',
                'quantity_limit' => null,
                'date_limit' => null,
                'country' => json_encode(['CN', 'SMY']),
                'usage' => json_encode(['Planting Material']),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category' => 1,
                'item_name' => 'MANGO',
                'addional_condition' => '',
                'quantity_limit' => null,
                'date_limit' => null,
                'country' => json_encode(['AU', 'CN', 'ID', 'MM', 'PK', 'PH', 'SWK', 'ZA', 'LK', 'TW', 'TH', 'US', 'VN']),
                'usage' => json_encode(['Planting Material']),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category' => 1,
                'item_name' => 'MANGOSTEEN',
                'addional_condition' => '',
                'quantity_limit' => null,
                'date_limit' => null,
                'country' => json_encode(['AU', 'SMY']),
                'usage' => json_encode(['Planting Material']),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category' => 1,
                'item_name' => 'RAMBUTAN',
                'addional_condition' => '',
                'quantity_limit' => null,
                'date_limit' => null,
                'country' => json_encode(['SWK', 'SMY']),
                'usage' => json_encode(['Planting Material']),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category' => 3,
                'item_name' => 'BELL PEPPER (CAPSICUM ANNUM)',
                'addional_condition' => '',
                'quantity_limit' => null,
                'date_limit' => null,
                'country' => json_encode(['AU', 'NL', 'VN']),
                'usage' => json_encode(['Planting Material']),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category' => 3,
                'item_name' => 'BIRD EYE CHILI (CAPSICUM ANNUM)',
                'addional_condition' => '',
                'quantity_limit' => null,
                'date_limit' => null,
                'country' => json_encode(['AU', 'CN', 'JP', 'TH', 'VN']),
                'usage' => json_encode(['Planting Material']),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category' => 3,
                'item_name' => 'FRESH GINGER',
                'addional_condition' => '',
                'quantity_limit' => null,
                'date_limit' => null,
                'country' => json_encode(['CN', 'SMY']),
                'usage' => json_encode(['Planting Material']),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category' => 3,
                'item_name' => 'FRESH ROUND CABBAGE',
                'addional_condition' => '',
                'quantity_limit' => null,
                'date_limit' => null,
                'country' => json_encode(['CN']),
                'usage' => json_encode(['Planting Material']),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category' => 6,
                'item_name' => 'DRIED CHILIES',
                'addional_condition' => '',
                'quantity_limit' => null,
                'date_limit' => null,
                'country' => json_encode(['CN', 'JP', 'TH', 'VN']),
                'usage' => json_encode(['Planting Material']),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category' => 6,
                'item_name' => 'DRIED TEA LEAVES',
                'addional_condition' => '',
                'quantity_limit' => null,
                'date_limit' => null,
                'country' => json_encode(['AR', 'CN', 'IN', 'ID', 'KE', 'PG', 'SWK', 'VN', 'SMY']),
                'usage' => json_encode(['Planting Material']),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category' => 6,
                'item_name' => 'FLOUR/STARCH (RICE, TAPIOCA, CORN, WHEAT, CASSAVA)',
                'addional_condition' => '',
                'quantity_limit' => null,
                'date_limit' => null,
                'country' => json_encode(['AU', 'CN', 'DK', 'FI', 'DE', 'HU', 'IN', 'LT', 'NL', 'RO', 'TH', 'US', 'SMY']),
                'usage' => json_encode(['Planting Material']),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category' => 6,
                'item_name' => 'LEGUME (GREEN MUNG BEAN,PEANUT, SESAME SEED, RED BEAN/ADZUKI BEAN, GROUNDNUT, YELLOW BAMBOO BEAN, GROUNDNUT, PEANUT) ',
                'addional_condition' => '',
                'quantity_limit' => null,
                'date_limit' => null,
                'country' => json_encode(['AU', 'CA', 'ZA', 'CN', 'EG', 'IN', 'MM', 'NZ', 'SG', 'ZA', 'TH', 'US', 'SMY']),
                'usage' => json_encode(['Planting Material']),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category' => 6,
                'item_name' => 'RAW COFFEE BEAN',
                'addional_condition' => '',
                'quantity_limit' => null,
                'date_limit' => null,
                'country' => json_encode(['ID', 'IT', 'SG', 'TW', 'VN', 'SMY']),
                'usage' => json_encode(['Planting Material']),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category' => 6,
                'item_name' => 'ROASTED COFFEE BEAN',
                'addional_condition' => '',
                'quantity_limit' => null,
                'date_limit' => null,
                'country' => json_encode(['ID', 'IT', 'SG', 'TW', 'VN', 'SMY']),
                'usage' => json_encode(['Planting Material']),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category' => 6,
                'item_name' => 'SOYBEAN',
                'addional_condition' => '',
                'quantity_limit' => null,
                'date_limit' => null,
                'country' => json_encode(['AR', 'AU', 'BE', 'CA', 'IN', 'NZ', 'US', 'SMY']),
                'usage' => json_encode(['Planting Material']),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category' => 6,
                'item_name' => 'RICE GRAIN',
                'addional_condition' => '',
                'quantity_limit' => null,
                'date_limit' => null,
                'country' => json_encode(['MM', 'VN', 'SMY']),
                'usage' => json_encode(['Planting Material']),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category' => 6,
                'item_name' => 'WHEAT, WHEAT GRAIN',
                'addional_condition' => '',
                'quantity_limit' => null,
                'date_limit' => null,
                'country' => json_encode(['AU', 'CA']),
                'usage' => json_encode(['Planting Material']),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category' => 2,
                'item_name' => 'BLOCKBOARD',
                'addional_condition' => '',
                'quantity_limit' => null,
                'date_limit' => null,
                'country' => json_encode(['AR', 'CM', 'CA', 'CN', 'ID', 'SWK', 'US', 'VN', 'SMY']),
                'usage' => json_encode(['Planting Material']),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category' => 2,
                'item_name' => 'DOOR',
                'addional_condition' => '',
                'quantity_limit' => null,
                'date_limit' => null,
                'country' => json_encode(['AR', 'CM', 'CA', 'CN', 'ID', 'SWK', 'US', 'VN', 'SMY']),
                'usage' => json_encode(['Planting Material']),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category' => 2,
                'item_name' => 'FINGER WOOD JOINT TIMBER',
                'addional_condition' => '',
                'quantity_limit' => null,
                'date_limit' => null,
                'country' => json_encode(['AR', 'CM', 'CA', 'CN', 'ID', 'SWK', 'US', 'VN', 'SMY']),
                'usage' => json_encode(['Planting Material']),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category' => 2,
                'item_name' => 'SAWN TIMBER',
                'addional_condition' => '',
                'quantity_limit' => null,
                'date_limit' => null,
                'country' => json_encode(['AR', 'CM', 'CA', 'CN', 'ID', 'SWK', 'US', 'VN', 'SMY']),
                'usage' => json_encode(['Planting Material']),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category' => 2,
                'item_name' => 'TEAK',
                'addional_condition' => '',
                'quantity_limit' => null,
                'date_limit' => null,
                'country' => json_encode(['AR', 'CM', 'CA', 'CN', 'ID', 'SWK', 'US', 'VN', 'SMY']),
                'usage' => json_encode(['Planting Material']),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category' => 2,
                'item_name' => 'PLYWOOD',
                'addional_condition' => '',
                'quantity_limit' => null,
                'date_limit' => null,
                'country' => json_encode(['AG', 'CM', 'CA', 'CN', 'ID', 'SWK', 'US', 'VN', 'SMY']),
                'usage' => json_encode(['Planting Material']),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category' => 2,
                'item_name' => 'WOOD TIMBER',
                'addional_condition' => '',
                'quantity_limit' => null,
                'date_limit' => null,
                'country' => json_encode(['AR', 'CM', 'CA', 'CN', 'ID', 'SWK', 'US', 'VN', 'SMY']),
                'usage' => json_encode(['Planting Material']),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category' => 7,
                'item_name' => 'BROKEN MAIZE',
                'addional_condition' => '',
                'quantity_limit' => null,
                'date_limit' => null,
                'country' => json_encode(['AR', 'IN', 'PK']),
                'usage' => json_encode(['Planting Material']),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category' => 7,
                'item_name' => 'BROKEN RICE',
                'addional_condition' => '',
                'quantity_limit' => null,
                'date_limit' => null,
                'country' => json_encode(['MM', 'SWK', 'VN', 'SMY']),
                'usage' => json_encode(['Planting Material']),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category' => 7,
                'item_name' => 'CHAFF (WHEATEN,LUCERNE)',
                'addional_condition' => '',
                'quantity_limit' => null,
                'date_limit' => null,
                'country' => json_encode(['AU', 'US', 'SMY']),
                'usage' => json_encode(['Planting Material']),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category' => 7,
                'item_name' => 'CANOLA MEAL',
                'addional_condition' => '',
                'quantity_limit' => null,
                'date_limit' => null,
                'country' => json_encode(['AU']),
                'usage' => json_encode(['Planting Material']),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category' => 7,
                'item_name' => 'CORN GLUTEN MEAL',
                'addional_condition' => '',
                'quantity_limit' => null,
                'date_limit' => null,
                'country' => json_encode(['AU', 'CN', 'IN', 'NL', 'PK', 'TR', 'US', 'SMY']),
                'usage' => json_encode(['Planting Material']),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category' => 7,
                'item_name' => 'DISTILLERS DRIED GRAINS WITH SOLUBLES (DDGS)',
                'addional_condition' => '',
                'quantity_limit' => null,
                'date_limit' => null,
                'country' => json_encode(['US']),
                'usage' => json_encode(['Planting Material']),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category' => 7,
                'item_name' => 'FISH FEED',
                'addional_condition' => '',
                'quantity_limit' => null,
                'date_limit' => null,
                'country' => json_encode(['CN', 'TH', 'VN', 'SMY']),
                'usage' => json_encode(['Planting Material']),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category' => 7,
                'item_name' => 'HAY (ALFALFA, WHEATEN, OATEN)',
                'addional_condition' => '',
                'quantity_limit' => null,
                'date_limit' => null,
                'country' => json_encode(['AU', 'US', 'SMY']),
                'usage' => json_encode(['Planting Material']),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category' => 7,
                'item_name' => 'SESAME MEAL',
                'addional_condition' => '',
                'quantity_limit' => null,
                'date_limit' => null,
                'country' => json_encode(['PK']),
                'usage' => json_encode(['Planting Material']),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category' => 7,
                'item_name' => 'SHIMP FEED',
                'addional_condition' => '',
                'quantity_limit' => null,
                'date_limit' => null,
                'country' => json_encode(['CN', 'TH', 'VN', 'SMY']),
                'usage' => json_encode(['Planting Material']),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category' => 7,
                'item_name' => 'SOYBEAN MEAL',
                'addional_condition' => '',
                'quantity_limit' => null,
                'date_limit' => null,
                'country' => json_encode(['AR', 'IN', 'PK', 'SG', 'UA', 'US', 'SMY']),
                'usage' => json_encode(['Planting Material']),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category' => 7,
                'item_name' => 'WHEAT POLLARD',
                'addional_condition' => '',
                'quantity_limit' => null,
                'date_limit' => null,
                'country' => json_encode(['AU', 'CA', 'JP', 'SMY']),
                'usage' => json_encode(['Planting Material']),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category' => 4,
                'item_name' => 'COVER CROP SEED',
                'addional_condition' => '',
                'quantity_limit' => null,
                'date_limit' => null,
                'country' => json_encode(['IN', 'ID', 'SMY']),
                'usage' => json_encode(['Planting Material']),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category' => 4,
                'item_name' => 'DURIAN SEEDLING',
                'addional_condition' => '',
                'quantity_limit' => null,
                'date_limit' => null,
                'country' => json_encode(['SWK', 'SMY']),
                'usage' => json_encode(['Planting Material']),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category' => 4,
                'item_name' => 'JACKFRUIT SEEDLING',
                'addional_condition' => '',
                'quantity_limit' => null,
                'date_limit' => null,
                'country' => json_encode(['SWK', 'SMY']),
                'usage' => json_encode(['Planting Material']),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category' => 4,
                'item_name' => 'OIL PALM',
                'addional_condition' => '',
                'quantity_limit' => null,
                'date_limit' => null,
                'country' => json_encode(['SWK', 'SMY']),
                'usage' => json_encode(['Planting Material']),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category' => 4,
                'item_name' => 'ORCHIDS ',
                'addional_condition' => '',
                'quantity_limit' => null,
                'date_limit' => null,
                'country' => json_encode(['CN', 'SWK', 'VN', 'SMY']),
                'usage' => json_encode(['Planting Material']),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category' => 4,
                'item_name' => 'PINEAPPLE SUCKER',
                'addional_condition' => '',
                'quantity_limit' => null,
                'date_limit' => null,
                'country' => json_encode(['SWK', 'SMY']),
                'usage' => json_encode(['Planting Material']),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category' => 4,
                'item_name' => 'PISIFERA POLLEN',
                'addional_condition' => '',
                'quantity_limit' => null,
                'date_limit' => null,
                'country' => json_encode(['SMY']),
                'usage' => json_encode(['Planting Material']),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category' => 4,
                'item_name' => 'RUZI GRASS',
                'addional_condition' => '',
                'quantity_limit' => null,
                'date_limit' => null,
                'country' => json_encode(['LA']),
                'usage' => json_encode(['Planting Material']),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category' => 4,
                'item_name' => 'SIGNAL GRASS',
                'addional_condition' => '',
                'quantity_limit' => null,
                'date_limit' => null,
                'country' => json_encode(['AU']),
                'usage' => json_encode(['Planting Material']),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category' => 4,
                'item_name' => 'VEGETABLE & FRUIT SEED',
                'addional_condition' => '',
                'quantity_limit' => null,
                'date_limit' => null,
                'country' => json_encode(['AU', 'CL', 'DK', 'IT', 'JP', 'ES', 'TH', 'US', 'US', 'SMY']),
                'usage' => json_encode(['Planting Material']),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category' => 5,
                'item_name' => 'COCO PEAT',
                'addional_condition' => '',
                'quantity_limit' => null,
                'date_limit' => null,
                'country' => json_encode(['CA', 'CN', 'DK', 'EE', 'FI', 'DE', 'IN', 'LV', 'LT', 'NL', 'NZ', 'PH', 'PL', 'TW']),
                'usage' => json_encode(['Planting Material']),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category' => 5,
                'item_name' => 'PEAT MOSS',
                'addional_condition' => '',
                'quantity_limit' => null,
                'date_limit' => null,
                'country' => json_encode(['CA', 'CN', 'DK', 'EE', 'FI', 'DE', 'IN', 'LV', 'LT', 'NL', 'NZ', 'PH', 'PL', 'LK', 'TW']),
                'usage' => json_encode(['Planting Material']),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category' => 5,
                'item_name' => 'SPHAGNUM',
                'addional_condition' => '',
                'quantity_limit' => null,
                'date_limit' => null,
                'country' => json_encode(['CA', 'CN', 'DK', 'EE', 'FI', 'DE', 'IN', 'LV', 'LT', 'NL', 'NZ', 'PH', 'PL', 'LK', 'TW']),
                'usage' => json_encode(['Planting Material']),
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);
    }
}
