server {
    listen 80;
    index index.php index.html;
    root /var/www/html/public;

    client_max_body_size 100M;

    location /storage/ {
        alias /var/www/html/public/storage/;
        access_log off;
        expires max;
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass qis_app_web:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;

        # 🔑 Force FastCGI to inform Laravel the request is secure
        # fastcgi_param HTTPS 'on';
        # fastcgi_param HTTP_X_FORWARDED_PROTO 'https';

        fastcgi_buffers 16 16k;
        fastcgi_buffer_size 32k;
    }

    location ~ /\.ht {
        deny all;
    }
}